application: task-bubbles
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  expiration: "7d"
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /robots\.txt
  expiration: "7d"
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /new
  script: new_task.app

- url: /task.*
  script: task.app

- url: .*
  script: task_bubbles.app

libraries:
- name: jinja2
  version: latest
