runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  expiration: "7d"
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /img
  expiration: "7d"
  static_dir: static/images

- url: /robots\.txt
  expiration: "7d"
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /css
  expiration: "1d"
  static_dir: static/css

- url: /js
  expiration: "1d"
  static_dir: static/js

- url: /task.*
  script: task.app

- url: .*
  script: task_bubbles.app
